const Routes = {
    Splash: 'Splash',
    SignUp: 'SignUp',
    Login: 'Login',
    ConfirmEmail: 'ConfirmEmail',
    InviteCode: 'InviteCode',
    ApproveAccount: 'ApproveAccount',
    ForgotPassword: 'ForgotPassword',
    PasswordRecovery: 'PasswordRecovery',
    ResetPassword: 'ResetPassword',
    ResetSuccess: 'ResetSuccess',
    Dashboard: 'Dashboard',
    History: 'History',
    Home: 'Home',
    Settings: 'Settings',
    Filter: 'Filter',
    HomeStack: 'HomeStack',
    HistoryStack: 'HistoryStack',
    SettingsStack: 'SettingsStack',
    HistoryDetail: 'HistoryDetail',
    NfcInfo: 'NfcInfo',
    ScanUnSuccess: 'ScanUnSuccess',
    ScanSuccess: 'ScanSuccess',
    ScanAgainInfo: 'ScanAgainInfo',
    AddDeviceId: 'AddDeviceId',
    DeviceIdUnSuccess: 'DeviceIdUnSuccess',
    ScanAfterAddIdScreen: 'ScanAfterAddIdScreen',
    AddLocationName: 'AddLocationName',
    AlreadySetCoordinate: 'AlreadySetCoordinate',
    ConfirmCoordinate: 'ConfirmCoordinate',
    EditProfile: 'EditProfile',
    UpdateName: 'UpdateName',
    UpdateEmail: 'UpdateEmail',
    ConfirmNameChange: 'ConfirmNameChange',
    RequestSubmit: 'RequestSubmit',
    UpdateOrganization: 'UpdateOrganization',
    ConfirmOrganizationChange: 'ConfirmOrganizationChange',
    NewCodeSubmit: 'NewCodeSubmit',
    ChangePassword:'ChangePassword',
    Notification:'Notification'


}

export default Routes