

const string = {
  APP_NAME: 'TracDisc',
  App_Version: 'App Version: ',
  Signup_Now: 'Signup Now',
  Signup: 'Signup',
  Confirm_Email: 'Confirm Email',
  Almost_done: 'Almost done!',
  Please_Enter_5_Didit_Number: 'Please enter the 5 digit verification code that was sent to your email:',

  //PlaceHodler
  Email: 'Email Address',
  Password: 'Password',
  FullName: 'Full Name',
  By_Signing_Up: 'By signing up, you agree with our',
  Terms_of_Service: 'Terms of Service',
  Privacy_Policy: 'Privacy Policy',
  And_Sign: '&',
  Space: ' ',
  SignUp: 'Signup',
  Forgot_Password: 'Forgot Password',
  Question: '?',
  Already_Have_Accout: 'Already have an account?',
  Dont_Have_Account: 'Don’t have an account?',
  Login: 'Login',
  Remember_Me: 'Remember Me',
  Didnt_Get_code: 'Didn’t get the code',
  Resend_Now: 'Resend Now',
  Continue: 'Continue',
  InviteCode: 'Invite code',
  Final_Step: 'Final step',
  Enter_Invite_Code: 'Enter your unique 6 digit invite code',
  InviteCode_Info1: 'This is a case sensitive 6 digit code issued by your organisation admin.',
  InviteCode_Info2: 'Was the invite code issued via email? Please try checking your spam folder.',
  InviteCode_Info3: 'If you still don’t know your invite code, contact your organisation admin.',
  Submit: 'Submit',
  Thank_You: 'Thank you!',
  Pending_Approval: 'Pending Approval',
  Registration_Is_Pending: 'Your registration is pending review.',
  Once_Approved_Able_Login: 'Once approved, you will be able to login.',
  Go_Back_To_Login: 'Go back to Login',
  Welcome: 'Welcome',
  Having_Trouble_Login: 'Having trouble logging in',
  Usernames_Form_Email: 'Usernames are in the form of email addresses.',
  Password_Case_Sensitive: 'Passwords are case sensitive.',
  Reset_Password_Add_Email: 'To reset your password, enter your original registration email address below.',
  If_Email_Linked_Warning: 'If this email is linked to your account, a recovery code will be sent.',
  Experiencing_Further_Warning: 'If you’re experiencing further issues, please contact your organisation admin.',
  To_Reset_Add_Below_Email: 'To reset your password, enter your original registration email address below.',
  Password_Recovery: 'Password Recovery',
  Check_Your_Email: 'Check your email',
  We_Have_Sent_Email: 'We have sent an email to:',
  Email_Linked_Code: 'If this email is linked to your account, it will contain a 5 digit recovery code.',
  Please_Enter_Code: 'Please enter the code:',
  Didnt_Get_Email: 'Didn’t get the email?',
  Cant_Find_Email_Warning: 'Can’t find the email? Was the email you provided correct? Please try checking your SPAM folder.',
  If_You_Still_Warning: 'If you still can’t log in, contact your organisation admin.',
  Reset_Password: 'Reset Password',
  Create_Password: 'Create new password',
  Password_Info: 'Your new password must be different from the old one.',
  Change_Password_Info: 'Your new password must be different from the old one. Remember both password must match!',
  Enter_Password: 'Enter your new password',
  Enter_Old_Password: 'Enter old password',
  Confirm_Password: 'Confirm your new password',
  Success: 'Success!',
  Password_Reset_Successfully: 'Password reset successfully',
  Return_To_Login: 'Return to Login',
  History: 'History',
  Home: 'Home',
  Account: 'Account',
  DeviceId: 'Device ID',
  Colon: ':',
  Comma: ',',
  Set_New_Coordinate: 'Set new coordinates',
  Set_Coordinate: 'Set Coordinates',
  MAC: 'MAC',
  Filter: 'Filter',
  Reset: 'Reset',
  To: 'to',
  showing_last_results: (length) => `Showing last ${length} scans`,
  showing_results: (length) => `Showing ${length} results`,
  App_Version: 'App Version',

  Enable_Location: 'Enable Location',
  Go_To_Settings: 'Go to settings',
  Enable_NFC: 'Enable NFC',
  We_Will_Need_Location_To_Start: 'We’ll need your location for you to start using the app',
  Please_Turn_On_NFC_To_Continue: 'NFC is turned off. Please turn on NFC to continue using the tracdisc app',
  Please_On_Location_From_Setting: 'Please turn on location from settings',
  Device_Not_Supported_NFC: 'Device not supported NFC feature',
  Place_Your_Phone: 'Place your phone near the device',
  Cancel: 'Cancel',
  Validating_Scan: 'Validating Scan',
  Please_Wait: 'Please wait..',
  This_Can_Take: 'This can take up to 10 seconds',
  Okay: 'Okay',
  Your_Scan_Was_Success: 'Your scan was successful!',
  Your_Scan_Was_UnSuccess: 'Your scan was unsuccessful!',
  Your_Last_Scan_Was_UnSuccess: 'Your last scan was successful!',
  Retry: 'Retry',
  Please_Retry_Action: 'Please retry the action.',
  Please_Try_Again: 'Please try again in 24 seconds.',
  Facing_Simmilar_Issue: 'If you’re facing similar issue repeatedly, please contact your admin.',
  Step2: 'Step 2',
  Step1: 'Step 1',
  Step3: 'Step 3',
  Step4: 'Step 4',
  Add_Device_ID: 'Add Device ID',
  Enter_The_Device_ID: 'This can be found printed on the device body or lid and consists of 2 sets of numbers.',
  E_G_4091: 'e.g. 55-4091',
  Unsuccessful: 'Unsuccessful!',
  Return: 'Return',
  Device_ID_Not_Found: 'Device ID not found.\nPlease contact admin.',
  Scan_The_Device: 'Scan the device',
  Place_Your_Phone_Near: 'Place your phone near the device to scan and set its coordinates',
  You_Are_About_To_Set: 'You’re about to set the device coordinates for',
  Name_The_Location: 'Name the location',
  Confirm: 'Confirm',
  Please_Confirm_The_DeviceID: 'Please confirm the device ID and coordinates to proceed',
  The_Coordinates_already_Set: 'The coordinates for this device are already set. Please confirm to proceed.',
  Do_You_Want_To_Set: 'Do you want to set new coordinates ?',
  This_Process_Can_Undone: 'This process can not be undone',
  Warning: 'Warning',
  Change: 'Change',
  Edit_Profile: 'Edit Profile',
  Logout: 'Logout',
  Name_Update_Under_Review: 'Name update request under review',
  Email_Update_Under_Review: 'Email update request under review',
  Update_Name: 'Update Name',
  Update_Email: 'Update Email',
  Confirm_Name_Change: 'Confirm Name Change',
  Confirm_Email_Change: 'Confirm Email Change',
  You_Changing_Name: 'You are changing your name',
  Your_Email_Address_Update: 'Enter your email address below to update',
  Your_Name_Under_Review: 'Your name update request is under review.',
  Your_Email_Under_Review: 'Your email update request is under review.',
  Pending_Approval_Admin: 'Pending approval from admin',
  Email_Only: 'Email',
  Note: 'Note',
  Verification_Code_To_New_Email: 'A verification code will be sent to your new email address',
  Email_Will_Update: 'Your email will be updated once the organisation admin verifies and approves the change.',
  Name_Will_Update: 'Your name will be updated once the organisation admin verifies and approves the change.',
  Cancel_Request: 'Cancel Request',
  Return_To_Profile: 'Return to Profile',
  Verify_Email_Update_Request: 'Your organisation admin needs to verify your email update request.',
  Verify_Name_Update_Request: 'Your organisation admin needs to verify your name update request.',
  We_Have_Your_Request: 'We have your request!',
  Update_Name: 'Update Name',
  From: 'From',
  To: 'To',
  You_Are_Changing_Name: 'You are changing your name',
  You_Changing_Organisation_ID: 'You are changing organisation ID',
  Name_Will_Change: 'Your name change will require organisation admin confirmation.',
  Update_Organization: 'Update Organization',
  Any_Changes_Organization_Require_Approve: 'Any changes made to organisation ID will require admin approval',
  Enter_New_ID: 'Enter new ID',
  Case_Sensitive_Info: 'This is a case sensitive 6 digit code usually issued by your organisation admin',
  Warninng_Invite_Code: 'You will not be able to use the app until your invite code has been approved by organisation admin.',
  Confirm_Whether_You_Wish: 'Please confirm whether you wish to proceed. Note: this process can not be undone',
  New_Organisation_Sent: 'Your new organisation ID has been sent to admin and is now under review',
  Change_Password: 'Change Password',
  Take_Selfie: 'Take Selfie',
  Upload_From_Photos:'Upload from photos',
  Notification:'Notification'



}






export { string }



